name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release Notes
        uses: Bullrich/generate-release-changelog@master
        id: ReleaseNotes

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          body: |
            ${{ steps.ReleaseNotes.outputs.changelog }}
          files: |
            readme.md
            license.txt
