name: Create Release

on:
  push:
    tags:
      - 'v[0-9]*'

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Validate Tag and Branch
        id: validation
        run: |
          TAG=$(git tag --contains HEAD | grep '^v[0-9]' | head -n 1)
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "🏷️ Tag for commit is: $TAG"
          echo "🕊️ Current branch is: $BRANCH"
          if [[ -z "$TAG" || "$BRANCH" != "main" ]]; then
            echo "is_valid_commit=false" >> $GITHUB_ENV
            echo "tag_name=''" >> $GITHUB_ENV
          else
            echo "is_valid_commit=true" >> $GITHUB_ENV
            echo "tag_name=$TAG" >> $GITHUB_ENV
          fi

      - name: Release Notes
        if: env.is_valid_commit == 'true'
        id: release-notes
        uses: Bullrich/generate-release-changelog@master

      - name: Release
        if: env.is_valid_commit == 'true'
        id: release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          name: ${{ env.tag_name }}
          tag_name: ${{ env.tag_name }}
          body: |
            ${{ steps.release-notes.outputs.changelog }}
          files: |
            readme.md
            README.md
            LICENSE
            license.txt
            CHANGELOG
            CHANGELOG.md
            changelog.md

      - name: Log Release Details
        if: env.is_valid_commit == 'true'
        run: |
          echo "📦 Successfully released: ${{ env.tag_name }}"
          echo "🔗 Release URL: ${{ steps.release.outputs.url }}"
          echo "🪪 Release ID: ${{ steps.release.outputs.id }}"
